"""Core value objects and configuration types shared by all Atrium agents.

These types are intentionally free of any heavy third-party dependency so that
they can be imported on the host control plane without pulling in inference or
HTTP stacks. The only external dependency is :mod:`semver`, used verbatim as the
agent version Value Object.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

# The agent version Value Object is a third-party ``semver.Version`` used as-is.
from semver import Version as VersionTag

__all__ = [
    "VersionTag",
    "NetworkMode",
    "GPURequest",
    "ExecutionResult",
    "SandboxConfig",
]


class NetworkMode(str, Enum):
    """Container network isolation policy.

    * ``NONE`` — no NIC at all (fully offline).
    * ``INTERNAL`` — only the host-local container<->container / control-plane
      LAN is reachable; the public internet (WAN) is blocked. This is the policy
      required for GPU-bearing inference containers.
    * ``BRIDGE`` — standard outbound bridge networking; WAN reachable.
    """

    NONE = "none"
    INTERNAL = "internal"
    BRIDGE = "bridge"


@dataclass(slots=True)
class GPURequest:
    """An NVIDIA Container Toolkit GPU passthrough request.

    Mirrors the information OpenShell needs to expose host GPUs to a sandbox via
    ``--gpu``. ``count == -1`` means "all visible GPUs".
    """

    count: int = -1
    capabilities: tuple[str, ...] = ("gpu", "utility", "compute")
    device_ids: Optional[tuple[str, ...]] = None

    def as_cli_flags(self) -> list[str]:
        """Render this request as OpenShell CLI flags."""
        flags: list[str] = ["--gpu"]
        if self.device_ids:
            flags += ["--gpu-devices", ",".join(self.device_ids)]
        elif self.count >= 0:
            flags += ["--gpu-count", str(self.count)]
        return flags


@dataclass(slots=True)
class ExecutionResult:
    """The result of running a single command inside a sandbox."""

    command: str
    exit_code: int
    stdout: str = ""
    stderr: str = ""
    duration_s: float = 0.0

    @property
    def succeeded(self) -> bool:
        """``True`` when the command exited with status 0."""
        return self.exit_code == 0


@dataclass(slots=True)
class SandboxConfig:
    """Isolation, resource and network configuration for an OpenShell sandbox.

    ``image`` defaults to ``None``; when unset, the agent falls back to its
    version-derived image name (``local-registry/<slug>:<version>``).
    """

    image: Optional[str] = None
    network: NetworkMode = NetworkMode.INTERNAL
    internal: bool = True
    device_requests: list[GPURequest] = field(default_factory=list)
    cpus: Optional[float] = None
    memory: Optional[str] = None
    env: dict[str, str] = field(default_factory=dict)
    volumes: dict[str, str] = field(default_factory=dict)
    workdir: str = "/workspace"
    policy_path: Optional[str] = None
    labels: dict[str, str] = field(default_factory=dict)

    @property
    def gpu_enabled(self) -> bool:
        """``True`` when at least one GPU passthrough request is present."""
        return bool(self.device_requests)

    @property
    def wan_allowed(self) -> bool:
        """``True`` only when this config would permit public internet egress."""
        return self.network == NetworkMode.BRIDGE and not self.internal

    def render_policy_yaml(self) -> str:
        """Render an OpenShell L7 network policy derived from this config.

        OpenShell enforces egress with hot-reloadable YAML policies (default:
        minimal outbound). ``INTERNAL``/``NONE`` deny all WAN egress while
        leaving host-local LAN/A2A reachable; ``BRIDGE`` permits egress. The
        exact OpenShell policy schema may differ between CLI versions; this
        renders a conservative, human-readable starting point that an operator
        can pin via ``policy_path``.
        """
        deny_wan = self.network in (NetworkMode.INTERNAL, NetworkMode.NONE) or self.internal
        egress = "deny" if deny_wan else "allow"
        lines = [
            "# Auto-generated by atrium.core.types.SandboxConfig.render_policy_yaml",
            "version: 1",
            "network:",
            f"  default_egress: {egress}",
            "  allow:",
            "    # host-local container<->container / control-plane is always permitted",
            "    - cidr: 127.0.0.0/8",
            "    - cidr: 10.0.0.0/8",
        ]
        if not deny_wan:
            lines.append("    - cidr: 0.0.0.0/0  # WAN egress (BRIDGE mode)")
        return "\n".join(lines) + "\n"
